"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { 
  Download,
  Copy,
  Check,
  FileJson,
  FileText,
  Share2,
  Clock
} from "lucide-react";
import { Button } from "./ui/button";
import type { WalletAnalysis } from "@/lib/privacy-engine";

interface ExportPanelProps {
  analysis: WalletAnalysis | null;
  address: string;
}

export function ExportPanel({ analysis, address }: ExportPanelProps) {
  const [copied, setCopied] = useState(false);
  const [exportFormat, setExportFormat] = useState<"json" | "summary">("json");

  if (!analysis) return null;
  
  // Use address prop if analysis.address is undefined
  const walletAddress = analysis.address || address;

  const generateJsonExport = () => {
    return JSON.stringify({
      exportedAt: new Date().toISOString(),
      version: "1.0",
      analysis: {
        address: walletAddress,
        privacyScore: analysis.privacyScore,
        transactionCount: analysis.transactionCount,
        uniqueInteractions: analysis.uniqueInteractions,
        risks: analysis.risks.map(r => ({
          id: r.id,
          severity: r.severity,
          title: r.title,
          description: r.description,
          confidence: r.confidence,
          category: r.category,
        })),
        rangeRiskScore: {
          score: analysis.rangeRiskScore.riskScore,
          level: analysis.rangeRiskScore.riskLevel,
        },
        mevExposure: analysis.mevExposure,
        temporalAnalysis: analysis.temporalAnalysis,
        aiSummary: analysis.aiSummary,
      },
    }, null, 2);
  };

  const generateSummaryExport = () => {
    const riskList = analysis.risks.map(r => 
      `- [${r.severity.toUpperCase()}] ${r.title} (${r.confidence}% confidence)`
    ).join('\n');

    return `# ECHO Privacy Analysis Report
Generated: ${new Date().toLocaleString()}

## Wallet Overview
- **Address:** ${walletAddress}
- **Privacy Score:** ${analysis.privacyScore}/100
- **Transactions Analyzed:** ${analysis.transactionCount}
- **Unique Interactions:** ${analysis.uniqueInteractions}

## AI Summary
${analysis.aiSummary.summary}

## Detected Risks
${riskList || 'No significant risks detected.'}

## Key Recommendations
${analysis.aiSummary.recommendations.map(r => `- ${r}`).join('\n')}

## MEV Exposure
- Detected: ${analysis.mevExposure.detected ? 'Yes' : 'No'}
- Count: ${analysis.mevExposure.count}
- Total Extracted: ${analysis.mevExposure.totalExtracted} lamports

## Temporal Patterns
- Patterns Detected: ${analysis.temporalAnalysis.hasPatterns ? 'Yes' : 'No'}
- Confidence: ${analysis.temporalAnalysis.confidence}%
${analysis.temporalAnalysis.commonHours.length > 0 
  ? `- Common Hours: ${analysis.temporalAnalysis.commonHours.map(h => {
      if (h === 0) return "12 AM";
      if (h === 12) return "12 PM";
      return h < 12 ? `${h} AM` : `${h - 12} PM`;
    }).join(', ')}`
  : ''
}

---
*Report generated by ECHO Gossip Chain - Solana Privacy Visualization Tool*
`;
  };

  const copyToClipboard = () => {
    const content = exportFormat === "json" ? generateJsonExport() : generateSummaryExport();
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const content = exportFormat === "json" ? generateJsonExport() : generateSummaryExport();
    const blob = new Blob([content], { 
      type: exportFormat === "json" ? "application/json" : "text/markdown" 
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `echo-analysis-${walletAddress.slice(0, 8)}-${Date.now()}.${exportFormat === "json" ? "json" : "md"}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-black/40 backdrop-blur-sm border border-blue-500/20 rounded-xl p-4 space-y-4"
    >
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Download className="h-4 w-4 text-blue-400" />
          <span className="text-sm font-mono text-blue-400">Export Analysis</span>
        </div>
        <div className="flex items-center gap-1 text-xs text-gray-500">
          <Clock className="h-3 w-3" />
          {new Date().toLocaleTimeString()}
        </div>
      </div>

      {/* Format Selection */}
      <div className="flex gap-2">
        <button
          onClick={() => setExportFormat("json")}
          className={`flex-1 p-2 rounded-lg border flex items-center justify-center gap-2 transition-colors ${
            exportFormat === "json"
              ? "bg-blue-500/20 border-blue-500/50 text-blue-400"
              : "bg-black/40 border-gray-700 text-gray-400 hover:border-gray-600"
          }`}
        >
          <FileJson className="h-4 w-4" />
          <span className="text-xs font-mono">JSON</span>
        </button>
        <button
          onClick={() => setExportFormat("summary")}
          className={`flex-1 p-2 rounded-lg border flex items-center justify-center gap-2 transition-colors ${
            exportFormat === "summary"
              ? "bg-blue-500/20 border-blue-500/50 text-blue-400"
              : "bg-black/40 border-gray-700 text-gray-400 hover:border-gray-600"
          }`}
        >
          <FileText className="h-4 w-4" />
          <span className="text-xs font-mono">Markdown</span>
        </button>
      </div>

      {/* Preview */}
      <div className="bg-black/60 rounded-lg p-3 border border-gray-700 max-h-32 overflow-y-auto">
        <pre className="text-xs text-gray-400 font-mono whitespace-pre-wrap">
          {exportFormat === "json" 
            ? generateJsonExport().slice(0, 300) + "..."
            : generateSummaryExport().slice(0, 300) + "..."
          }
        </pre>
      </div>

      {/* Action Buttons */}
      <div className="flex gap-2">
        <Button
          onClick={copyToClipboard}
          variant="outline"
          size="sm"
          className="flex-1 border-blue-500/30 text-blue-400 hover:bg-blue-500/10"
        >
          {copied ? (
            <>
              <Check className="h-3 w-3 mr-1" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="h-3 w-3 mr-1" />
              Copy
            </>
          )}
        </Button>
        <Button
          onClick={downloadFile}
          size="sm"
          className="flex-1 bg-blue-600 hover:bg-blue-700 text-white"
        >
          <Download className="h-3 w-3 mr-1" />
          Download
        </Button>
      </div>
    </motion.div>
  );
}
